import { AbstractControl } from "@angular/forms";

export const getJobTitles = [
        { job:'Management',             title:[ 'General Manager', 'Transport Manager' ] },
        { job:'Human Resorces',         title:[ 'Hr Manager', 'Hr Assistant' ] },
        { job:'Administration',         title:[ 'Fleet Administrator', 'Transport Supervisor', 'Transport Planner', 'Clerical' ] },
        { job:'Driver',                 title:[ 'Driver C+E - Artic', 'Driver C - Rigid', 'Driver C1 - 7.5', 'Driver B - Non Hgv', 'Shunter' ] },
        { job:'Warehouse',              title:[ 'Forklift Driver', 'Warehouse Operative' ] },
];
export const getNoticeboardSections = [
    { department:'Management',          title:[ 'Management News', 'Section Two', 'Section Three'] },
    { department:'Engagement',          title:[ 'Engagement News', 'Section Two', 'Section Three'] },
    { department:'Union',               title:[ 'Union News', 'Section Two', 'Section Three'] },
    { department:'Health & Safety',     title:[ 'Health & Safety News', 'Section Two', 'Section Three'] }
];
export const getAdminValues = [
    { navBar:'General',         section:[   {button : 0,display:true, employee:true, admin:true, name:'Canteen Display'}]},
    { navBar:'Management',      section:[   {button : 1,display:true, employee:true, admin:true, name:'Notice Board'},
                                            {button : 2,display:false, employee:true, admin:false, name:'Rota'},
                                            {button : 3,display:false, employee:true, admin:false, name:'Start Times'},
                                            {button : 4,display:false, employee:true, admin:false, name:'Holiday'},
                                            {button : 5,display:false, employee:false, admin:false, name:'Button 5'},
                                            {button : 6,display:false, employee:false, admin:false, name:'Button 6'}]},
    { navBar:'Engagement',      section:[   {button : 7,display:true, employee:true, admin:true, name:'Notice Board'},
                                            {button : 8,display:true, employee:true, admin:true, name:'Calender'},
                                            {button : 9,display:false, employee:false, admin:false, name:'Button 3'},
                                            {button :10,display:false, employee:false, admin:false, name:'Button 4'},
                                            {button :11,display:false, employee:false, admin:false, name:'Button 5'},
                                            {button :12,display:false, employee:false, admin:false, name:'Button 6'}]},
    { navBar:'Union',           section:[   {button :13,display:true, employee:true, admin:true, name:'Notice Board'},
                                            {button :14,display:true, employee:true, admin:false, name:'USDAW'},
                                            {button :15,display:true, employee:true, admin:false, name:'UNITE'},
                                            {button :16,display:false, employee:false, admin:false, name:'Button 4'},
                                            {button :17,display:false, employee:false, admin:false, name:'Button 5'},
                                            {button :18,display:false, employee:false, admin:false, name:'Button 6'}]},
    { navBar:'Health & Safety', section:[   {button :19,display:true, employee:true, admin:true, name:'Notice Board'},
                                            {button :20,display:false, employee:true, admin:false, name:'Store Risk Assesments'},
                                            {button :21,display:false, employee:false, admin:false, name:'Button 3'},
                                            {button :22,display:false, employee:false, admin:false, name:'Button 4'},
                                            {button :23,display:false, employee:false, admin:false, name:'Button 5'},
                                            {button :24,display:false, employee:false, admin:false, name:'Button 6'}]},
    { navBar:'Admin Employee',  section:[   {button :25,display:false, employee:true, admin:false, name:'Employee Profile'},
                                            {button :26,display:false, employee:true, admin:false, name:'Change Password'},
                                            {button :27,display:false, employee:false, admin:false, name:'Request Uniform'},
                                            {button :28,display:false, employee:false, admin:false, name:'Request Holiday'},
                                            {button :29,display:false, employee:false, admin:false, name:'Button 5'},
                                            {button :30,display:false, employee:false, admin:false, name:'Button 6'}]},
    { navBar:'Admin Supervisor',section:[   {button :31,display:false, employee:false, admin:true, name:'Add New Noticeboard - Management'},
                                            {button :32,display:false, employee:false, admin:true, name:'Add New Noticeboard - Engagement'},
                                            {button :33,display:false, employee:false, admin:true, name:'Add New Noticeboard - Union'},
                                            {button :34,display:false, employee:false, admin:true, name:'Add New Noticeboard - Health & Safety'},
                                            {button :35,display:false, employee:false, admin:true, name:'Add Employee Holiday'},
                                            {button :36,display:false, employee:false, admin:true, name:'Upload Start Times'},
                                            {button :37,display:false, employee:false, admin:true, name:'Add Employee Rota Comment'},
                                            {button :38,display:false, employee:false, admin:false, name:'Button 5'},
                                            {button :39,display:false, employee:false, admin:false, name:'Button 6'}]},
    { navBar:'Admin Manager',   section:[   {button :40,display:false, employee:false, admin:true, name:'Add Welcome Screen - Management'},
                                            {button :41,display:false, employee:false, admin:true, name:'Add Welcome Screen - Engagement'},
                                            {button :42,display:false, employee:false, admin:true, name:'Add Welcome Screen - Union'},
                                            {button :43,display:false, employee:false, admin:true, name:'Add Welcome Screen - Health & Safety'},
                                            {button :44,display:false, employee:false, admin:true, name:'Update Welcome Screen - Management'},
                                            {button :45,display:false, employee:false, admin:true, name:'Update Welcome Screen - Engagement'},
                                            {button :46,display:false, employee:false, admin:true, name:'Update Welcome Screen - Union'},
                                            {button :47,display:false, employee:false, admin:true, name:'Update Welcome Screen - Health & Safety'},
                                            {button :48,display:false, employee:false, admin:false, name:'Button 3'},
                                            {button :49,display:false, employee:false, admin:true, name:'Reset Employee Password'},
                                            {button :50,display:false, employee:false, admin:false, name:'Button 5'},
                                            {button :51,display:false, employee:false, admin:false, name:'Button 6'}]}, 
    { navBar:'Admin HR',        section:[   {button :52,display:false, employee:false, admin:false, name:'Update Employee Information'},
                                            {button :53,display:false, employee:false, admin:false, name:'Button 2'},
                                            {button :54,display:false, employee:false, admin:true, name:'Add New Employee'},
                                            {button :55,display:false, employee:false, admin:true, name:'Add New Rota'},
                                            {button :56,display:false, employee:false, admin:false, name:'Button 5'},
                                            {button :57,display:false, employee:false, admin:false, name:'Button 6'}]},
    { navBar:'Admin Site',      section:[   {button :58,display:false, employee:false, admin:false, name:'Button 1'},
                                            {button :59,display:false, employee:false, admin:false, name:'Button 2'},
                                            {button :60,display:false, employee:false, admin:false, name:'Button 3'},
                                            {button :61,display:false, employee:false, admin:false, name:'Button 4'},
                                            {button :62,display:false, employee:false, admin:true, name:'Update Site Info'},
                                            {button :63,display:false, employee:false, admin:true, name:'Add New Site'}]}
];